### ISSUE TITLE
yoo

### ISSUE THREAD

**Issue by xen00** [stormzy1337/Splitgate-Queue-Bypass#1]
damn man nice source man you really made that?

**Comment by stormzyidk** [comment]
> damn man nice source man you really made that?

read the first line of the cpp file

**Comment by stormzyidk** [comment]
i literally gave you full credit and said pasted

**Comment by xen00** [comment]
oh i didnt see, whoops my bad

**Comment by xen00** [comment]
case closed, good day sir
